import json
import logging
import os
import re
from typing import Any, Dict, List

from dotenv import load_dotenv

try:
    from langchain_google_genai import ChatGoogleGenerativeAI
except Exception:
    ChatGoogleGenerativeAI = None

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))

logger = logging.getLogger(__name__)


class RecommendationAgent:
    def __init__(self) -> None:
        self.llm = None

    def _get_llm(self):
        if ChatGoogleGenerativeAI is None:
            return None
        api_key = os.getenv("GOOGLE_API_KEY", "")
        if not api_key or "your_gemini_api_key_here" in api_key:
            return None
        return ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=api_key, temperature=0.3)

    def generate(self, risk_analysis: Dict[str, Any], retrieved_context: List[str], customer_history: List[Dict[str, Any]] = None, customer_id: str = "") -> List[Dict[str, Any]]:
        try:
            # Get already approved actions from memory
            approved_actions = []
            try:
                from memory.memory_manager import get_approved_actions
                approved_actions = get_approved_actions(customer_id) if customer_id else []
                logger.info(f"Already approved actions for {customer_id}: {approved_actions}")
            except Exception as e:
                logger.warning(f"Could not fetch approved actions: {e}")

            llm = self._get_llm()
            if llm is None:
                logger.warning("No Gemini LLM available (missing/invalid GOOGLE_API_KEY) — using fallback recommendations")
                return self._tag_source(
                    self._fallback_recommendations(risk_analysis, retrieved_context, customer_history or [], approved_actions),
                    "fallback_no_llm",
                )

            prompt = (
                "You are a customer success strategist. Follow this structure: "
                "Step 1: Review the risk analysis scores and signals. "
                "Step 2: Match signals to relevant playbook guidance. "
                "Step 3: Consider what actions were already tried from history. "
                "Step 4: Generate 3 specific, actionable recommendations. "
                "Step 5: Score each by confidence and assign priority. "
                "Return ONLY a JSON array of exactly 3 objects with these fields: "
                "action, reasoning, confidence (0.0-1.0), priority (high/medium/low), "
                "evidence (array of strings), timeline, owner."
                f"\n\nRisk analysis: {json.dumps(risk_analysis, default=str)}"
                f"\n\nPlaybooks: {json.dumps(retrieved_context, default=str)}"
                f"\n\nHistory: {json.dumps(customer_history or [], default=str)}"
                f"\n\nALREADY APPROVED ACTIONS - DO NOT repeat these: {json.dumps(approved_actions)}"
                f"\n\nGenerate 3 DIFFERENT recommendations that have not been done yet."
            )

            try:
                response = llm.invoke(prompt)
            except Exception as llm_exc:
                logger.error(f"Gemini call failed: {llm_exc} — using fallback recommendations")
                return self._tag_source(
                    self._fallback_recommendations(risk_analysis, retrieved_context, customer_history or [], approved_actions),
                    "fallback_llm_error",
                )

            content = response.content if hasattr(response, "content") else str(response)
            parsed = self._safe_json_parse(content)
            if parsed and len(parsed) >= 3:
                items = parsed[:3]
                logger.info("Recommendations generated by Gemini")
                return self._tag_source([self._normalize_item(item) for item in items], "gemini")

            logger.warning("Gemini response could not be parsed into 3 items — using fallback recommendations")
            return self._tag_source(
                self._fallback_recommendations(risk_analysis, retrieved_context, customer_history or [], approved_actions),
                "fallback_parse_error",
            )

        except Exception as exc:
            logger.exception("Recommendation generation failed")
            return self._tag_source(
                self._fallback_recommendations(risk_analysis, retrieved_context, customer_history or [], []),
                "fallback_exception",
            )

    @staticmethod
    def _tag_source(items: List[Dict[str, Any]], source: str) -> List[Dict[str, Any]]:
        for item in items:
            item["source"] = source
        return items


    def _fallback_recommendations(self, risk_analysis: Dict[str, Any], retrieved_context: List[str], customer_history: List[Dict[str, Any]], approved_actions: List[str] = None) -> List[Dict[str, Any]]:
        approved_actions = approved_actions or []
        previous_actions = {item.get("action", "").lower() for item in customer_history if isinstance(item, dict)}
        skip = previous_actions | {a.lower() for a in approved_actions}

        # Read real signals out of risk_analysis so the fallback responds to
        # the actual transcript instead of being a fixed list every time.
        churn_score = float(risk_analysis.get("churn_risk_score", 0) or 0)
        is_expansion = bool(risk_analysis.get("expansion_opportunity"))
        signals = " ".join(str(s).lower() for s in (risk_analysis.get("key_signals") or []))
        context_text = " ".join(str(c).lower() for c in (retrieved_context or []))
        combined = signals + " " + context_text

        candidates: List[Dict[str, Any]] = []

        if churn_score >= 60:
            candidates.append({
                "action": "Schedule a recovery call with the customer within 24 hours",
                "reasoning": f"Churn risk score is {churn_score:.0f}%, indicating an urgent recovery conversation is needed.",
                "confidence": min(0.95, 0.6 + churn_score / 200),
                "priority": "high",
                "evidence": (risk_analysis.get("key_signals") or ["Elevated churn risk detected"])[:2],
                "timeline": "Within 24 hours",
                "owner": "Senior CSM",
            })

        if "support" in combined or "ticket" in combined or "issue" in combined:
            candidates.append({
                "action": "Escalate open support issues to engineering with an SLA commitment",
                "reasoning": "The interaction references unresolved support issues, a leading churn indicator.",
                "confidence": 0.85,
                "priority": "high",
                "evidence": ["Customer raised support/ticket issues"],
                "timeline": "Within 48 hours",
                "owner": "Technical Account Manager",
            })

        if "onboard" in combined or "confus" in combined or "training" in combined:
            candidates.append({
                "action": "Share a personalized onboarding and adoption plan",
                "reasoning": "Signals indicate onboarding confusion or adoption gaps.",
                "confidence": 0.8,
                "priority": "medium",
                "evidence": ["Onboarding/adoption gap signals detected"],
                "timeline": "Within 3 days",
                "owner": "Onboarding Specialist",
            })

        if "renew" in combined or "pricing" in combined or "price" in combined or "contract" in combined:
            candidates.append({
                "action": "Send ROI report and renewal business case to the economic buyer",
                "reasoning": "Renewal or pricing concerns were raised — proactively reinforcing value reduces churn risk.",
                "confidence": 0.78,
                "priority": "high" if churn_score >= 50 else "medium",
                "evidence": ["Renewal/pricing signals detected"],
                "timeline": "Within 1 week",
                "owner": "Account Executive",
            })

        if is_expansion or "expand" in combined or "additional" in combined or "more seats" in combined:
            candidates.append({
                "action": "Introduce expansion options aligned to the customer's stated use case",
                "reasoning": "Positive engagement and expansion signals suggest an upsell conversation is timely.",
                "confidence": 0.75,
                "priority": "low",
                "evidence": ["Expansion/growth signal detected"],
                "timeline": "Within 1 week",
                "owner": "Account Executive",
            })

        # Always-available generic fallbacks to top up to 3 if specific
        # signals didn't produce enough candidates.
        generic = [
            {
                "action": "Set up a weekly health-check cadence for the next 30 days",
                "reasoning": "Regular touchpoints surface issues early and build relationship trust.",
                "confidence": 0.7,
                "priority": "medium",
                "evidence": ["General retention best practice"],
                "timeline": "Starting this week",
                "owner": "CSM",
            },
            {
                "action": "Create an executive success roadmap for the account",
                "reasoning": "A documented roadmap aligns the customer and internal teams on next steps.",
                "confidence": 0.68,
                "priority": "medium",
                "evidence": ["General account-management best practice"],
                "timeline": "Within 1 week",
                "owner": "Account Executive",
            },
            {
                "action": "Loop in the executive sponsor for a direct relationship check-in",
                "reasoning": "Executive engagement strengthens the relationship on at-risk or high-value accounts.",
                "confidence": 0.65,
                "priority": "low",
                "evidence": ["General executive-engagement best practice"],
                "timeline": "Within 2 weeks",
                "owner": "VP Customer Success",
            },
        ]

        all_candidates = candidates + generic
        filtered = [item for item in all_candidates if item["action"].lower() not in skip]

        # De-duplicate by action text while preserving order
        seen = set()
        deduped = []
        for item in filtered:
            key = item["action"].lower()
            if key not in seen:
                seen.add(key)
                deduped.append(item)

        return deduped[:3]

    def _normalize_item(self, item: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "action": item.get("action", "Follow up with the customer"),
            "reasoning": item.get("reasoning", "No reasoning provided"),
            "confidence": float(item.get("confidence", 0.7)),
            "priority": item.get("priority", "medium"),
            "evidence": item.get("evidence", []),
            "timeline": item.get("timeline", "Within 24 hours"),
            "owner": item.get("owner", "CSM"),
        }

    def _safe_json_parse(self, content: str) -> List[Dict[str, Any]]:
        try:
            text = re.sub(r"```json|```", "", content).strip()
            return json.loads(text)
        except Exception:
            return []